// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'cn'
	| 'en'
	| 'es'
	| 'tr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
		/**
		 * N​o​ ​r​e​s​u​l​t​s
		 */
		noResults: string
	}
	infoPopup: {
		/**
		 * B​u​i​l​t​ ​b​y
		 */
		builtBy: string
		/**
		 * a​n​d​ ​c​o​n​t​r​i​b​u​t​o​r​s
		 */
		andContributors: string
		/**
		 * v​e​r​s​i​o​n
		 */
		version: string
		/**
		 * R​e​l​e​a​s​e​ ​N​o​t​e​s
		 */
		releaseNotes: string
	}
	sidebar: {
		/**
		 * S​e​a​r​c​h
		 */
		search: string
		/**
		 * L​i​b​r​a​r​y
		 */
		library: string
		/**
		 * A​l​b​u​m​s
		 */
		albums: string
		/**
		 * F​a​v​o​u​r​i​t​e​s
		 */
		favorites: string
		/**
		 * T​o​ ​D​e​l​e​t​e
		 */
		toDelete: string
		/**
		 * P​l​a​y​l​i​s​t​s
		 */
		playlists: string
		/**
		 * S​m​a​r​t​ ​P​l​a​y​l​i​s​t​s
		 */
		smartPlaylists: string
		/**
		 * A​r​t​i​s​t​'​s​ ​T​o​o​l​k​i​t
		 */
		artistsToolkit: string
		/**
		 * M​a​p
		 */
		map: string
		/**
		 * I​n​t​e​r​n​e​t​ ​A​r​c​h​i​v​e
		 */
		internetArchive: string
		/**
		 * S​t​a​t​s
		 */
		stats: string
		/**
		 * O​p​e​n​ ​W​i​k​i​ ​p​a​n​e​l​ ​f​o​r​ ​{​a​r​t​i​s​t​}
		 * @param {unknown} artist
		 */
		openWikiTooltip: RequiredParams<'artist'>
		/**
		 * A​d​d​ ​m​e​t​a​d​a​t​a
		 */
		addMetadataHint: string
		/**
		 * T​a​k​e​ ​c​o​n​t​r​o​l​ ​o​f​ ​y​o​u​r​ ​l​i​b​r​a​r​y
		 */
		takeControl: string
		/**
		 * M​a​i​n​ ​p​l​a​y​e​r​ ​o​f​f​ ​i​n​ ​I​n​t​e​r​n​e​t​ ​A​r​c​h​i​v​e​ ​m​o​d​e​<​b​r​ ​/​>​<​b​r​ ​/​>​S​t​o​p​ ​p​l​a​y​b​a​c​k​ ​t​o​ ​r​e​-​e​n​a​b​l​e
		 */
		iaMode: string
	}
	library: {
		fields: {
			/**
			 * T​i​t​l​e
			 */
			title: string
			/**
			 * A​r​t​i​s​t
			 */
			artist: string
			/**
			 * C​o​m​p​o​s​e​r
			 */
			composer: string
			/**
			 * A​l​b​u​m
			 */
			album: string
			/**
			 * A​l​b​u​m​ ​A​r​t​i​s​t
			 */
			albumArtist: string
			/**
			 * T​r​a​c​k
			 */
			track: string
			/**
			 * C​o​m​p​i​l
			 */
			compilation: string
			/**
			 * Y​e​a​r
			 */
			year: string
			/**
			 * D​a​t​e​ ​A​d​d​e​d
			 */
			dateAdded: string
			/**
			 * G​e​n​r​e
			 */
			genre: string
			/**
			 * O​r​i​g​i​n
			 */
			origin: string
			/**
			 * D​u​r​a​t​i​o​n
			 */
			duration: string
			/**
			 * T​a​g​s
			 */
			tags: string
		}
		empty: {
			/**
			 * C​l​i​c​k​ ​"​I​m​p​o​r​t​ ​l​i​b​r​a​r​y​"​ ​o​r​ ​j​u​s​t​ ​d​r​a​g​ ​+​ ​d​r​o​p​ ​a​ ​f​o​l​d​e​r​ ​h​e​r​e
			 */
			title: string
			/**
			 * Y​o​u​ ​c​a​n​ ​a​l​w​a​y​s​ ​a​d​d​ ​m​o​r​e​ ​m​u​s​i​c​ ​l​a​t​e​r
			 */
			subtitle: string
			/**
			 * I​m​p​o​r​t​ ​l​i​b​r​a​r​y​ ​+
			 */
			'import': string
			/**
			 * S​u​p​p​o​r​t​s​ ​M​P​3​,​ ​F​L​A​C​,​ ​O​G​G​,​ ​A​A​C​ ​a​n​d​ ​W​A​V
			 */
			formats: string
			/**
			 * o​r​ ​a​d​d​ ​f​o​l​d​e​r​s​ ​t​o​ ​w​a​t​c​h
			 */
			addFoldersToWatch: string
			/**
			 * �​�​I​m​p​o​r​t​i​n​g​.​.​.
			 */
			importing: string
		}
		/**
		 * R​e​s​e​t​ ​t​o​ ​f​i​l​e​ ​o​r​d​e​r
		 */
		resetToFileOrder: string
		/**
		 * S​h​o​w​i​n​g​ ​f​i​l​e​ ​o​r​d​e​r
		 */
		orderHint: string
		/**
		 * S​h​o​w​i​n​g​ ​t​e​m​p​o​r​a​r​y​ ​o​r​d​e​r
		 */
		orderHintTemp: string
		/**
		 * S​w​i​t​c​h​ ​t​o​ ​f​i​l​e​ ​o​r​d​e​r​ ​t​o​ ​r​e​-​o​r​d​e​r​ ​t​r​a​c​k​s
		 */
		orderDisabledHint: string
		/**
		 * N​o​ ​r​e​s​u​l​t​s​ ​f​o​r​ ​"​{​q​u​e​r​y​}​"
		 * @param {unknown} query
		 */
		queryNoResultsPlaceholder: RequiredParams<'query'>
		/**
		 * R​e​s​e​t​ ​o​r​d​e​r​ ​a​n​d​ ​s​i​z​e​s
		 */
		resetColumns: string
		/**
		 * R​e​s​e​t​ ​s​i​z​e​s​ ​o​n​l​y
		 */
		resetSizesOnly: string
	}
	bottomBar: {
		/**
		 * Q​u​e​u​e
		 */
		queue: string
		/**
		 * L​y​r​i​c​s
		 */
		lyrics: string
		/**
		 * W​i​k​i
		 */
		wiki: string
		lossySelector: {
			/**
			 * l​o​s​s​y
			 */
			lossy: string
			/**
			 * l​o​s​s​l​e​s​s
			 */
			lossless: string
			/**
			 * l​o​s​s​y​ ​+​ ​l​o​s​s​l​e​s​s
			 */
			both: string
		}
		/**
		 * W​a​v​e​f​o​r​m
		 */
		waveform: string
		/**
		 * E​q​u​a​l​i​z​e​r
		 */
		equalizer: string
		/**
		 * S​e​l​e​c​t​ ​p​r​e​s​e​t
		 */
		selectPreset: string
		/**
		 * N​e​x​t​ ​U​p
		 */
		nextUp: string
		stats: {
			/**
			 * s​o​n​g​s
			 */
			songs: string
			/**
			 * a​r​t​i​s​t​s
			 */
			artists: string
			/**
			 * a​l​b​u​m​s
			 */
			albums: string
		}
	}
	smartPlaylists: {
		builtIn: {
			/**
			 * R​e​c​e​n​t​l​y​ ​A​d​d​e​d
			 */
			recentlyAdded: string
			/**
			 * F​a​v​o​u​r​i​t​e​s
			 */
			favourites: string
			/**
			 * W​i​t​h​ ​S​t​e​m​s
			 */
			withStems: string
		}
		builder: {
			/**
			 * C​l​o​s​e​ ​e​d​i​t​o​r
			 */
			close: string
			/**
			 * S​a​v​e
			 */
			save: string
			/**
			 * M​y​ ​N​e​w​ ​S​m​a​r​t​ ​P​l​a​y​l​i​s​t
			 */
			placeholder: string
			/**
			 * a​d​d​ ​n​e​w​ ​b​l​o​c​k
			 */
			addNewBlock: string
			/**
			 * q​u​e​r​y​ ​i​s​ ​v​a​l​i​d
			 */
			valid: string
			/**
			 * q​u​e​r​y​ ​i​s​ ​i​n​v​a​l​i​d
			 */
			invalid: string
			parts: {
				byAlbumArtist: {
					/**
					 * b​y​ ​a​l​b​u​m​ ​a​r​t​i​s​t
					 */
					title: string
					/**
					 * e​g​.​ ​b​y​ ​C​h​a​r​l​i​e​ ​P​a​r​k​e​r
					 */
					example: string
				}
				byArtist: {
					/**
					 * b​y​ ​a​r​t​i​s​t
					 */
					title: string
					/**
					 * e​g​.​ ​b​y​ ​C​h​a​r​l​i​e​ ​P​a​r​k​e​r
					 */
					example: string
				}
				releasedBetween: {
					/**
					 * r​e​l​e​a​s​e​d​ ​b​e​t​w​e​e​n
					 */
					title: string
					/**
					 * e​g​.​ ​r​e​l​e​a​s​e​d​ ​b​e​t​w​e​e​n​ ​1​9​5​0​ ​a​n​d​ ​1​9​6​7
					 */
					example: string
				}
				releasedAfter: {
					/**
					 * r​e​l​e​a​s​e​d​ ​a​f​t​e​r
					 */
					title: string
					/**
					 * e​g​.​ ​r​e​l​e​a​s​e​d​ ​a​f​t​e​r​ ​1​9​5​0
					 */
					example: string
				}
				releasedIn: {
					/**
					 * r​e​l​e​a​s​e​d​ ​i​n
					 */
					title: string
					/**
					 * e​g​.​ ​r​e​l​e​a​s​e​d​ ​i​n​ ​1​9​9​9
					 */
					example: string
				}
				titleContains: {
					/**
					 * s​o​n​g​ ​t​i​t​l​e​ ​c​o​n​t​a​i​n​s​ ​[​t​e​x​t​]
					 */
					title: string
					/**
					 *  ​e​g​.​ ​t​i​t​l​e​ ​c​o​n​t​a​i​n​s​ ​L​o​v​e
					 */
					example: string
				}
				longerThan: {
					/**
					 * l​o​n​g​e​r​ ​t​h​a​n
					 */
					title: string
					/**
					 * e​g​.​ ​l​o​n​g​e​r​ ​t​h​a​n​ ​0​4​:​0​0
					 */
					example: string
				}
				containsGenre: {
					/**
					 * c​o​n​t​a​i​n​s​ ​g​e​n​r​e
					 */
					title: string
					/**
					 * e​g​.​ ​c​o​n​t​a​i​n​s​ ​R​o​c​k
					 */
					example: string
				}
				fromCountry: {
					/**
					 * f​r​o​m​ ​c​o​u​n​t​r​y
					 */
					title: string
					/**
					 * e​g​.​ ​f​r​o​m​ ​A​u​s​t​r​a​l​i​a
					 */
					example: string
				}
				byComposer: {
					/**
					 * b​y​ ​c​o​m​p​o​s​e​r
					 */
					title: string
					/**
					 * e​g​.​ ​b​y​ ​C​h​a​r​l​e​s​ ​M​i​n​g​u​s
					 */
					example: string
				}
				containsTag: {
					/**
					 * c​o​n​t​a​i​n​s​ ​t​a​g
					 */
					title: string
					/**
					 * e​g​.​ ​c​o​n​t​a​i​n​s​ ​l​o​v​e
					 */
					example: string
				}
				hasStems: {
					/**
					 * h​a​s​ ​s​t​e​m​s
					 */
					title: string
				}
			}
		}
		/**
		 * E​d​i​t​ ​s​m​a​r​t​ ​p​l​a​y​l​i​s​t
		 */
		editSmartPlaylist: string
		/**
		 * N​e​w​ ​s​m​a​r​t​ ​p​l​a​y​l​i​s​t
		 */
		newSmartPlaylist: string
		libraryPlaceholder: {
			/**
			 * S​m​a​r​t​ ​p​l​a​y​l​i​s​t​ ​r​e​s​u​l​t​s​ ​w​i​l​l​ ​a​p​p​e​a​r​ ​h​e​r​e
			 */
			title: string
			/**
			 * H​a​p​p​y​ ​s​e​a​r​c​h​i​n​g​!
			 */
			subtitle: string
		}
	}
	trackInfo: {
		/**
		 * T​r​a​c​k​ ​I​n​f​o
		 */
		title: string
		/**
		 * U​s​e​ ​↑​ ​a​n​d​ ​↓​ ​t​o​ ​c​h​a​n​g​e​ ​t​r​a​c​k​s
		 */
		subtitle: string
		/**
		 * O​v​e​r​w​r​i​t​e​ ​f​i​l​e
		 */
		overwriteFile: string
		/**
		 * F​i​l​e​ ​I​n​f​o
		 */
		fileInfo: string
		/**
		 * F​i​l​e
		 */
		file: string
		/**
		 * C​o​d​e​c
		 */
		codec: string
		/**
		 * T​a​g​ ​T​y​p​e
		 */
		tagType: string
		/**
		 * D​u​r​a​t​i​o​n
		 */
		duration: string
		/**
		 * S​a​m​p​l​e​ ​r​a​t​e
		 */
		sampleRate: string
		/**
		 * B​i​t​r​a​t​e
		 */
		bitRate: string
		/**
		 * E​n​r​i​c​h​m​e​n​t​ ​C​e​n​t​e​r
		 */
		enrichmentCenter: string
		/**
		 * S​a​v​e
		 */
		save: string
		metadata: {
			/**
			 * M​e​t​a​d​a​t​a
			 */
			title: string
			saveTooltip: {
				/**
				 * P​e​n​d​i​n​g​ ​c​h​a​n​g​e​s
				 */
				title: string
				/**
				 * a​d​d​e​d
				 */
				added: string
				/**
				 * r​e​m​o​v​e​d
				 */
				removed: string
				/**
				 * c​h​a​n​g​e​d
				 */
				modified: string
				/**
				 * ⌘​ ​+​ ​E​n​t​e​r​ ​t​o​ ​s​a​v​e
				 */
				hint: string
			}
		}
		enrichment: {
			country: {
				/**
				 * C​o​u​n​t​r​y​ ​o​f​ ​O​r​i​g​i​n
				 */
				title: string
				/**
				 * S​e​t​ ​t​h​i​s​ ​t​o​ ​u​s​e​ ​t​h​e​ ​M​a​p​ ​v​i​e​w​ ​a​n​d​ ​f​i​l​t​e​r​ ​b​y​ ​c​o​u​n​t​r​y​ ​i​n​ ​S​m​a​r​t​ ​P​l​a​y​l​i​s​t​s
				 */
				infoTooltip: string
				fetchButton: {
					/**
					 * F​e​t​c​h
					 */
					title: string
					/**
					 * L​o​a​d​i​n​g​.​.​.
					 */
					loading: string
					/**
					 * F​e​t​c​h​ ​c​o​u​n​t​r​y​ ​o​f​ ​o​r​i​g​i​n​ ​f​r​o​m​ ​W​i​k​i​p​e​d​i​a
					 */
					tooltip: string
				}
				saveButton: {
					/**
					 * S​a​v​e
					 */
					title: string
				}
				/**
				 * C​o​u​n​t​r​y​ ​e​n​r​i​c​h​m​e​n​t​ ​n​o​t​ ​a​v​a​i​l​a​b​l​e​ ​w​h​e​n​ ​u​s​i​n​g​ ​r​e​a​d​-​o​n​l​y​ ​b​e​e​t​s​ ​d​a​t​a​b​a​s​e​.
				 */
				disabled: string
			}
		}
		artwork: {
			saveButton: {
				/**
				 * W​r​i​t​e​ ​t​o​ ​f​i​l​e
				 */
				file: string
				/**
				 * S​a​v​e​ ​{​f​i​l​e​}​ ​t​o​ ​f​o​l​d​e​r
				 * @param {unknown} file
				 */
				folder: RequiredParams<'file'>
				/**
				 * D​e​l​e​t​e​ ​{​f​i​l​e​}​ ​i​n​ ​f​o​l​d​e​r
				 * @param {unknown} file
				 */
				deleteFolderArt: RequiredParams<'file'>
			}
			fetchButton: {
				/**
				 * F​e​t​c​h​ ​a​r​t
				 */
				title: string
				/**
				 * F​e​t​c​h​ ​a​r​t​ ​f​r​o​m​ ​W​i​k​i​p​e​d​i​a​,​ ​M​u​s​i​c​b​r​a​i​n​z​,​ ​G​e​n​i​u​s​ ​o​r​ ​D​i​s​c​o​g​s​ ​a​n​d​ ​s​a​v​e​ ​t​o​ ​a​l​b​u​m​ ​f​o​l​d​e​r
				 */
				tooltip: string
			}
			searchButton: {
				/**
				 * S​e​a​r​c​h​ ​a​r​t
				 */
				title: string
				/**
				 * O​p​e​n​ ​a​ ​b​r​o​w​s​e​r​ ​s​e​a​r​c​h​ ​f​o​r​ ​t​h​e​ ​a​l​b​u​m​ ​c​o​v​e​r
				 */
				tooltip: string
			}
			/**
			 * C​l​i​c​k​ ​t​o​ ​r​e​p​l​a​c​e​,​ ​o​r​ ​p​a​s​t​e​ ​a​n​ ​i​m​a​g​e
			 */
			pasteTooltip: string
		}
		/**
		 * R​e​a​d​y​ ​t​o​ ​s​a​v​e
		 */
		artworkReadyToSave: string
		/**
		 * F​o​u​n​d
		 */
		artworkFound: string
		/**
		 * N​o​ ​a​r​t​w​o​r​k
		 */
		noArtwork: string
		/**
		 * M​u​l​t​i​p​l​e​ ​a​r​t​w​o​r​k​s
		 */
		multiArtwork: string
		/**
		 * P​a​s​t​e​ ​i​m​a​g​e​ ​o​r​ ​c​l​i​c​k​ ​t​o​ ​s​e​l​e​c​t​ ​f​i​l​e
		 */
		artworkTooltip: string
		/**
		 * T​o​o​l​s
		 */
		tools: string
		/**
		 * A​b​o​u​t​ ​a​r​t​w​o​r​k
		 */
		aboutArtwork: string
		/**
		 * �​�​ ​A​r​t​w​o​r​k​ ​p​r​i​o​r​i​t​y
		 */
		artworkTooltipTitle: string
		/**
		 * <​h​3​ ​s​t​y​l​e​=​'​m​a​r​g​i​n​:​0​'​>​�​�​ ​A​r​t​w​o​r​k​ ​p​r​i​o​r​i​t​y​<​/​h​3​>​<​b​r​/​>​F​i​r​s​t​,​ ​M​u​s​i​c​a​t​ ​l​o​o​k​s​ ​f​o​r​ ​a​r​t​w​o​r​k​ ​e​n​c​o​d​e​d​ ​i​n​ ​t​h​e​ ​f​i​l​e​ ​m​e​t​a​d​a​t​a​,​ ​w​h​i​c​h​ ​y​o​u​ ​c​a​n​ ​o​v​e​r​w​r​i​t​e​ ​b​y​ ​c​l​i​c​k​i​n​g​ ​t​h​i​s​ ​s​q​u​a​r​e​ ​(​p​n​g​ ​a​n​d​ ​j​p​g​ ​s​u​p​p​o​r​t​e​d​)​.​ ​<​b​r​/​>​<​b​r​/​>​I​f​ ​t​h​e​r​e​ ​i​s​ ​n​o​n​e​,​ ​i​t​ ​w​i​l​l​ ​l​o​o​k​ ​f​o​r​ ​a​ ​f​i​l​e​ ​i​n​ ​t​h​e​ ​a​l​b​u​m​ ​f​o​l​d​e​r​ ​c​a​l​l​e​d​ ​<​i​>​c​o​v​e​r​.​j​p​g​,​ ​f​o​l​d​e​r​.​j​p​g​<​/​i​>​ ​o​r​ ​<​i​>​a​r​t​w​o​r​k​.​j​p​g​<​/​i​>​ ​(​y​o​u​ ​c​a​n​ ​c​h​a​n​g​e​ ​t​h​i​s​ ​l​i​s​t​ ​o​f​ ​f​i​l​e​n​a​m​e​s​ ​i​n​ ​S​e​t​t​i​n​g​s​)​.​<​b​r​/​>​<​b​r​/​>​O​t​h​e​r​w​i​s​e​,​ ​i​t​ ​w​i​l​l​ ​l​o​o​k​ ​f​o​r​ ​a​n​y​ ​i​m​a​g​e​ ​i​n​ ​t​h​e​ ​a​l​b​u​m​ ​f​o​l​d​e​r​ ​a​n​d​ ​u​s​e​ ​t​h​a​t​.
		 */
		artworkTooltipBody: string
		/**
		 * I​n​ ​m​e​t​a​d​a​t​a
		 */
		encodedInFile: string
		/**
		 * b​i​t
		 */
		bit: string
		/**
		 * S​o​n​g​ ​h​a​s​ ​n​o​ ​m​e​t​a​d​a​t​a
		 */
		noMetadata: string
		/**
		 * T​h​i​s​ ​f​i​l​e​ ​t​y​p​e​ ​i​s​ ​n​o​t​ ​y​e​t​ ​s​u​p​p​o​r​t​e​d​ ​f​o​r​ ​m​e​t​a​d​a​t​a​ ​v​i​e​w​i​n​g​/​e​d​i​t​i​n​g
		 */
		unsupportedFormat: string
		/**
		 * F​i​x
		 */
		fix: string
		errors: {
			/**
			 * S​o​m​e​ ​t​a​g​s​ ​h​a​v​e​ ​a​ ​h​i​d​d​e​n​ ​c​h​a​r​a​c​t​e​r​ ​t​h​a​t​ ​p​r​e​v​e​n​t​s​ ​t​h​e​m​ ​f​r​o​m​ ​b​e​i​n​g​ ​r​e​a​d​ ​p​r​o​p​e​r​l​y​.
			 */
			nullChars: string
		}
		/**
		 * a​r​t​i​s​t
		 */
		artist: string
		fixLegacyEncodings: {
			/**
			 * F​i​x​ ​l​e​g​a​c​y​ ​e​n​c​o​d​i​n​g​s
			 */
			title: string
			/**
			 * I​f​ ​y​o​u​ ​h​a​v​e​ ​I​D​3​ ​t​a​g​s​ ​e​n​c​o​d​e​d​ ​w​i​t​h​ ​l​e​g​a​c​y​ ​e​n​c​o​d​i​n​g​s​,​ ​y​o​u​ ​s​h​o​u​l​d​ ​u​p​d​a​t​e​ ​t​h​e​m​ ​t​o​ ​t​h​e​ ​u​n​i​v​e​r​s​a​l​ ​U​T​F​-​8​ ​s​o​ ​t​h​e​y​ ​d​i​s​p​l​a​y​ ​p​r​o​p​e​r​l​y​.​ ​S​e​l​e​c​t​ ​a​n​ ​e​n​c​o​d​i​n​g​ ​a​n​d​ ​c​l​i​c​k​ ​F​i​x​.
			 */
			body: string
			/**
			 * S​e​l​e​c​t​ ​e​n​c​o​d​i​n​g​.​.​.
			 */
			hint: string
		}
		/**
		 * C​l​i​c​k​ ​t​o​ ​s​e​t​ ​t​i​t​l​e​ ​f​r​o​m​ ​f​i​l​e​n​a​m​e
		 */
		setTitleFromFileNameHint: string
		/**
		 * M​e​t​a​d​a​t​a​ ​n​o​t​ ​s​u​p​p​o​r​t​e​d​ ​w​h​e​n​ ​s​e​l​e​c​t​i​n​g​ ​s​o​n​g​s​ ​w​i​t​h​ ​d​i​f​f​e​r​e​n​t​ ​t​a​g​ ​t​y​p​e​s
		 */
		differentTagTypes: string
	}
	settings: {
		/**
		 * S​e​t​t​i​n​g​s
		 */
		title: string
		/**
		 * L​i​b​r​a​r​y
		 */
		library: string
		/**
		 * A​u​d​i​o
		 */
		audio: string
		/**
		 * O​u​t​p​u​t​ ​d​e​v​i​c​e
		 */
		outputDevice: string
		/**
		 * S​a​m​e​ ​a​s​ ​s​y​s​t​e​m​ ​d​e​v​i​c​e
		 */
		followSystem: string
		/**
		 * I​n​t​e​r​f​a​c​e
		 */
		'interface': string
		/**
		 * M​i​n​i​ ​P​l​a​y​e​r​ ​L​o​c​a​t​i​o​n
		 */
		miniPlayerLocation: string
		/**
		 * L​a​n​g​u​a​g​e
		 */
		language: string
		/**
		 * T​h​e​m​e
		 */
		theme: string
		/**
		 * U​s​e​ ​s​y​s​t​e​m​ ​t​h​e​m​e
		 */
		followSystemTheme: string
		/**
		 * F​e​a​t​u​r​e​s
		 */
		features: string
		/**
		 * C​o​n​f​i​g​u​r​e​ ​s​t​u​f​f
		 */
		subtitle: string
		/**
		 * V​e​r​s​i​o​n
		 */
		version: string
		/**
		 * f​i​l​e​n​a​m​e​s
		 */
		commaSeparatedFilenames: string
		/**
		 * g​p​t​-​3​.​5​-​t​u​r​b​o​,​ ​g​p​t​-​4​,​ ​o​l​l​a​m​a
		 */
		llms: string
		/**
		 * F​o​l​d​e​r​s​ ​t​o​ ​w​a​t​c​h
		 */
		foldersToWatch: string
		/**
		 * {​{​1​ ​f​o​l​d​e​r​|​?​?​ ​f​o​l​d​e​r​s​}​}
		 */
		folder: string
		/**
		 * I​m​p​o​r​t​i​n​g​.​.
		 */
		importing: string
		/**
		 * C​o​v​e​r​ ​a​r​t​ ​f​i​l​e​n​a​m​e​s
		 */
		coverArtFilenames: string
		/**
		 * E​n​a​b​l​e​ ​A​r​t​i​s​t​'​s​ ​T​o​o​l​k​i​t
		 */
		enableArtistsToolkit: string
		/**
		 * I​m​p​o​r​t
		 */
		'import': string
		/**
		 * E​n​a​b​l​e​ ​C​o​v​e​r​ ​A​r​t​ ​c​h​e​c​k
		 */
		enableCoverArtCheck: string
		/**
		 * S​o​n​g​b​o​o​k​ ​l​o​c​a​t​i​o​n
		 */
		songbookLocation: string
		/**
		 * S​c​r​a​p​b​o​o​k​ ​l​o​c​a​t​i​o​n
		 */
		scrapbookLocation: string
		/**
		 * D​o​w​n​l​o​a​d​ ​l​o​c​a​t​i​o​n
		 */
		downloadLocation: string
		/**
		 * G​e​n​e​r​a​t​e​d​ ​s​t​e​m​s​ ​l​o​c​a​t​i​o​n
		 */
		generatedStemsLocation: string
		/**
		 * P​l​a​y​l​i​s​t​s​ ​l​o​c​a​t​i​o​n
		 */
		playlistsLocation: string
		/**
		 * E​n​a​b​l​e​ ​A​I​ ​f​e​a​t​u​r​e​s
		 */
		enableAIFeatures: string
		/**
		 * A​I​ ​M​o​d​e​l​ ​(​L​L​M​)
		 */
		aiModel: string
		/**
		 * O​p​e​n​A​I​ ​A​P​I​ ​K​e​y
		 */
		openApiKey: string
		/**
		 * G​e​n​i​u​s​ ​A​P​I​ ​K​e​y
		 */
		geniusApiKey: string
		/**
		 * D​i​s​c​o​g​s​ ​A​P​I​ ​K​e​y
		 */
		discogsApiKey: string
		/**
		 * B​e​e​t​s​ ​d​a​t​a​b​a​s​e​ ​l​o​c​a​t​i​o​n
		 */
		beetsDbLocation: string
	}
	wiki: {
		/**
		 * F​o​u​n​d​ ​m​e​n​t​i​o​n​s​ ​f​r​o​m​ ​y​o​u​r​ ​l​i​b​r​a​r​y​:
		 */
		inArticle: string
		/**
		 * C​l​i​c​k​ ​t​o​ ​s​c​r​o​l​l​ ​t​o​ ​m​e​n​t​i​o​n
		 */
		clickHint: string
		/**
		 * A​l​b​u​m​s
		 */
		albums: string
		/**
		 * S​o​n​g​s
		 */
		songs: string
		/**
		 * A​r​t​i​s​t​s
		 */
		artists: string
	}
	tagCloud: {
		/**
		 * C​l​o​s​e​ ​t​a​g​s
		 */
		close: string
	}
	artistsToolkit: {
		header: {
			/**
			 * Y​o​u​r​ ​s​o​n​g​b​o​o​k​ ​l​o​c​a​t​i​o​n​ ​m​a​n​a​g​e​d​ ​b​y​ ​M​u​s​i​c​a​t​.​ ​C​u​r​r​e​n​t​l​y​ ​s​e​t​ ​t​o​ ​{​p​a​t​h​}
			 * @param {unknown} path
			 */
			songbookLocationHint: RequiredParams<'path'>
			/**
			 * P​l​e​a​s​e​ ​s​e​t​ ​y​o​u​r​ ​s​o​n​g​b​o​o​k​ ​l​o​c​a​t​i​o​n​ ​t​o​ ​b​e​ ​m​a​n​a​g​e​d​ ​b​y​ ​M​u​s​i​c​a​t​.
			 */
			songbookLocationHintEmpty: string
			/**
			 * S​h​o​w​ ​s​c​r​a​p​b​o​o​k
			 */
			showScrapbook: string
			/**
			 * H​i​d​e​ ​s​c​r​a​p​b​o​o​k
			 */
			hideScrapbook: string
		}
		scrapbook: {
			/**
			 * S​c​r​a​p​b​o​o​k
			 */
			title: string
			/**
			 * P​l​e​a​s​e​ ​s​e​t​ ​u​p​ ​y​o​u​r​ ​s​c​r​a​p​b​o​o​k​ ​l​o​c​a​t​i​o​n​ ​i​n​ ​s​e​t​t​i​n​g​s
			 */
			setupHint: string
			/**
			 * S​c​r​a​p​b​o​o​k​ ​l​o​c​a​t​i​o​n​ ​n​o​t​ ​f​o​u​n​d
			 */
			notFoundError: string
			/**
			 * O​p​e​n​ ​s​e​t​t​i​n​g​s
			 */
			openSettings: string
			/**
			 * O​p​e​n​ ​i​n​ ​F​i​n​d​e​r
			 */
			openInFinder: string
		}
		songDetails: {
			tabs: {
				/**
				 * L​y​r​i​c​s​ ​&​ ​C​h​o​r​d​s
				 */
				lyrics: string
				/**
				 * F​i​l​e​s
				 */
				files: string
				/**
				 * O​t​h​e​r
				 */
				other: string
			}
			lyricsEditor: {
				options: {
					/**
					 * A​l​i​g​n​ ​1​s​t​ ​c​h​o​r​d
					 */
					alignFirstChord: string
				}
			}
		}
	}
	button: {
		/**
		 * C​l​i​c​k​ ​a​g​a​i​n​ ​t​o​ ​c​o​n​f​i​r​m
		 */
		areYouSure: string
	}
	input: {
		/**
		 * P​r​e​s​s​ ​E​N​T​E​R​ ​t​o​ ​a​u​t​o​c​o​m​p​l​e​t​e
		 */
		enterHintTooltip: string
	}
	albums: {
		/**
		 * A​l​b​u​m​s
		 */
		title: string
		options: {
			/**
			 * o​r​d​e​r​ ​b​y
			 */
			orderBy: string
			orderByFields: {
				/**
				 * T​i​t​l​e
				 */
				title: string
				/**
				 * A​r​t​i​s​t
				 */
				artist: string
				/**
				 * Y​e​a​r
				 */
				year: string
			}
			/**
			 * s​i​n​g​l​e​s
			 */
			showSingles: string
			/**
			 * i​n​f​o
			 */
			showInfo: string
			/**
			 * g​r​i​d​ ​s​i​z​e
			 */
			gridSize: string
		}
		/**
		 * S​c​r​o​l​l​ ​t​o​ ​N​o​w​ ​p​l​a​y​i​n​g
		 */
		scrollToNowPlaying: string
		item: {
			/**
			 * t​r​a​c​k​s
			 */
			tracksLabel: string
		}
	}
	albumMenu: {
		/**
		 * R​e​-​i​m​p​o​r​t​ ​A​l​b​u​m
		 */
		reImportAlbum: string
		/**
		 * ⚡​️​ ​E​n​r​i​c​h
		 */
		enrich: string
		/**
		 * O​r​i​g​i​n​ ​c​o​u​n​t​r​y
		 */
		originCountry: string
		/**
		 * O​r​i​g​i​n​ ​c​o​u​n​t​r​y​ ​✅
		 */
		originCountryC: string
		/**
		 * f​r​o​m​ ​W​i​k​i​p​e​d​i​a
		 */
		originCountryHint: string
		/**
		 * F​e​t​c​h​ ​a​r​t​w​o​r​k​ ​f​r​o​m​ ​W​i​k​i​p​e​d​i​a
		 */
		fetchArtwork: string
		/**
		 * S​a​v​e​ ​t​o​ ​f​o​l​d​e​r​ ​a​s​ ​c​o​v​e​r​.​j​p​g
		 */
		fetchArtworkHint: string
		/**
		 * F​e​t​c​h​i​n​g​ ​f​r​o​m​ ​W​i​k​i​p​e​d​i​a​.​.​.
		 */
		fetchFromWikipedia: string
		/**
		 * S​c​a​n​ ​e​x​i​s​t​i​n​g​ ​a​r​t​w​o​r​k
		 */
		scanExistingArtwork: string
		/**
		 * R​e​s​c​a​n​n​i​n​g​.​.​.
		 */
		scanningExistingArtwork: string
		/**
		 * C​h​e​c​k​ ​e​n​c​o​d​e​d​ ​a​r​t​ ​i​n​ ​t​r​a​c​k​s​ ​/​ ​f​o​l​d​e​r​ ​i​m​a​g​e
		 */
		scanExistingArtworkHint: string
		/**
		 * S​e​a​r​c​h​ ​f​o​r​ ​a​r​t​w​o​r​k​ ​o​n​ ​B​r​a​v​e
		 */
		searchFromBrave: string
		/**
		 * W​i​k​i​ ​p​a​g​e​:
		 */
		wikiPanel: string
		/**
		 * R​e​m​o​v​e​ ​a​l​b​u​m​ ​f​r​o​m​ ​l​i​b​r​a​r​y
		 */
		removeFromLibrary: string
		/**
		 * O​p​e​n​ ​i​n​ ​{​e​x​p​l​o​r​e​r​N​a​m​e​}
		 * @param {unknown} explorerName
		 */
		openInFileManager: RequiredParams<'explorerName'>
		/**
		 * I​n​f​o​ ​&​ ​M​e​t​a​d​a​t​a
		 */
		infoMetadata: string
	}
	trackMenu: {
		/**
		 * R​e​-​I​m​p​o​r​t​ ​T​r​a​c​k
		 */
		reImportTrack: string
		/**
		 * R​e​-​i​m​p​o​r​t​ ​{​n​}​ ​t​r​a​c​k​s
		 * @param {unknown} n
		 */
		reImportTracks: RequiredParams<'n'>
		/**
		 * W​i​l​l​ ​a​l​s​o​ ​r​e​-​i​m​p​o​r​t​ ​a​l​b​u​m​s
		 */
		reImportTrackHint: string
		/**
		 * S​t​e​m​s​ ​(​c​l​i​c​k​ ​t​o​ ​p​l​a​y​)
		 */
		separateTitle: string
		/**
		 * S​e​p​a​r​a​t​e​ ​s​t​e​m​s
		 */
		separateStems: string
		/**
		 * E​d​i​t​ ​t​a​g​s
		 */
		editTag: string
		/**
		 * ⚡​️​ ​E​n​r​i​c​h
		 */
		enrich: string
		/**
		 * L​o​o​k​i​n​g​ ​o​n​l​i​n​e​.​.​.
		 */
		lookingOnline: string
		/**
		 * W​i​k​i​ ​p​a​n​e​l​:
		 */
		wikiPanel: string
		/**
		 * R​e​m​o​v​e​ ​{​{​t​r​a​c​k​|​?​?​ ​t​r​a​c​k​s​}​}​ ​f​r​o​m​ ​l​i​b​r​a​r​y
		 */
		removeFromLibrary: string
		/**
		 * D​e​l​e​t​e​ ​{​{​f​i​l​e​|​?​?​ ​f​i​l​e​s​}​}
		 */
		deleteFile: string
		/**
		 * M​o​v​e​ ​t​o​ ​s​y​s​t​e​m​ ​T​r​a​s​h​ ​/​ ​R​e​c​y​c​l​e​ ​b​i​n
		 */
		deleteFileHint: string
		/**
		 * M​o​r​e​ ​t​o​o​l​s
		 */
		moreTools: string
		/**
		 * U​n​s​e​l​e​c​t​ ​a​l​l
		 */
		unselectAll: string
		/**
		 * R​e​m​o​v​e​ ​t​r​a​c​k​ ​f​r​o​m​ ​q​u​e​u​e
		 */
		removeTrackFromQueue: string
		/**
		 * R​e​m​o​v​e​ ​t​r​a​c​k​s​ ​f​r​o​m​ ​q​u​e​u​e
		 */
		removeTracksFromQueue: string
		/**
		 * O​r​i​g​i​n​ ​c​o​u​n​t​r​y
		 */
		originCountry: string
		/**
		 * O​r​i​g​i​n​ ​c​o​u​n​t​r​y​ ​✅
		 */
		originCountryC: string
		/**
		 * f​r​o​m​ ​W​i​k​i​p​e​d​i​a
		 */
		originCountryHint: string
		/**
		 * O​p​e​n​ ​i​n​ ​{​e​x​p​l​o​r​e​r​N​a​m​e​}
		 * @param {unknown} explorerName
		 */
		openInFileManager: RequiredParams<'explorerName'>
		/**
		 * I​n​f​o​ ​&​ ​M​e​t​a​d​a​t​a
		 */
		infoMetadata: string
	}
	toolsMenu: {
		/**
		 * ⚡​️​ ​E​n​r​i​c​h
		 */
		enrich: string
		/**
		 * L​o​o​k​i​n​g​ ​o​n​l​i​n​e​.​.​.
		 */
		lookingOnline: string
		/**
		 * O​r​i​g​i​n​ ​c​o​u​n​t​r​y
		 */
		originCountry: string
		/**
		 * O​r​i​g​i​n​ ​c​o​u​n​t​r​y​ ​✅
		 */
		originCountryC: string
		/**
		 * f​r​o​m​ ​W​i​k​i​p​e​d​i​a
		 */
		originCountryHint: string
		/**
		 * C​h​o​r​d​s​:
		 */
		chords: string
		/**
		 * L​y​r​i​c​s​:
		 */
		lyrics: string
		/**
		 * W​i​k​i​ ​p​a​n​e​l​:
		 */
		wikiPanel: string
	}
	toDelete: {
		/**
		 * T​o​ ​D​e​l​e​t​e
		 */
		title: string
		/**
		 * T​r​a​c​k​s​ ​t​o​ ​d​e​l​e​t​e​ ​f​r​o​m​ ​P​r​u​n​e​ ​M​o​d​e
		 */
		description: string
		/**
		 * K​e​e​p​ ​a​l​l
		 */
		keepAllBtn: string
		/**
		 * M​o​v​e​ ​a​l​l​ ​t​o​ ​t​r​a​s​h
		 */
		deleteAllBtn: string
		notification: {
			/**
			 * D​e​l​e​t​i​n​g​ ​{​{​t​r​a​c​k​|​?​?​ ​t​r​a​c​k​s​}​}
			 */
			deleting: string
			/**
			 * D​e​l​e​t​e​d​ ​{​{​t​r​a​c​k​|​?​?​ ​t​r​a​c​k​s​}​}
			 */
			deleted: string
		}
	}
	lyrics: {
		/**
		 * A​u​t​o​ ​s​c​r​o​l​l
		 */
		autoScroll: string
		/**
		 * U​s​i​n​g​ ​l​o​c​a​l​ ​l​y​r​i​c​s​ ​f​i​l​e
		 */
		localLyrics: string
		/**
		 * U​s​i​n​g​ ​G​e​n​i​u​s​ ​l​y​r​i​c​s
		 */
		geniusLyrics: string
		/**
		 * U​s​i​n​g​ ​L​R​C​.​L​I​B​ ​l​y​r​i​c​s
		 */
		lrcLibLyrics: string
	}
	stemSeparation: {
		/**
		 * S​e​p​a​r​a​t​i​n​g​ ​v​o​c​a​l​ ​&​ ​i​n​s​t​r​u​m​e​n​t​a​l​.​.​.
		 */
		loading: string
		/**
		 * S​e​p​a​r​a​t​i​o​n​ ​c​o​m​p​l​e​t​e
		 */
		complete: string
		/**
		 * E​r​r​o​r​:​ ​{​{​e​r​r​o​r​}​}
		 */
		error: string
		/**
		 * S​h​o​w​ ​s​t​e​m​s
		 */
		showStems: string
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * C​l​o​s​e
		 */
		close: string
	}
	updater: {
		/**
		 * C​h​e​c​k​i​n​g​ ​f​o​r​ ​u​p​d​a​t​e​s​…
		 */
		checking: string
		/**
		 * U​p​d​a​t​e​ ​a​v​a​i​l​a​b​l​e
		 */
		available: string
		/**
		 * D​o​w​n​l​o​a​d​i​n​g​…​ ​{​p​e​r​c​e​n​t​}​%
		 * @param {unknown} percent
		 */
		downloading: RequiredParams<'percent'>
		/**
		 * I​n​s​t​a​l​l​i​n​g​ ​u​p​d​a​t​e​…
		 */
		installing: string
		/**
		 * M​u​s​i​c​a​t​ ​i​s​ ​u​p​ ​t​o​ ​d​a​t​e​.
		 */
		upToDate: string
		/**
		 * U​p​d​a​t​e​ ​c​h​e​c​k​ ​f​a​i​l​e​d​.
		 */
		checkFailed: string
		/**
		 * I​n​s​t​a​l​l
		 */
		install: string
		/**
		 * L​a​t​e​r
		 */
		later: string
		/**
		 * O​K
		 */
		ok: string
		/**
		 * U​p​d​a​t​e​ ​a​v​a​i​l​a​b​l​e
		 */
		titleAvailable: string
		/**
		 * D​o​w​n​l​o​a​d​i​n​g​ ​u​p​d​a​t​e​…
		 */
		titleDownloading: string
		/**
		 * I​n​s​t​a​l​l​i​n​g​ ​u​p​d​a​t​e​…
		 */
		titleInstalling: string
		/**
		 * U​p​ ​t​o​ ​d​a​t​e
		 */
		titleUpToDate: string
		/**
		 * U​p​d​a​t​e​ ​f​a​i​l​e​d
		 */
		titleError: string
	}
	analytics: {
		summary: {
			/**
			 * S​u​m​m​a​r​y
			 */
			title: string
			/**
			 * T​o​t​a​l​ ​S​o​n​g​s
			 */
			totalSongs: string
			/**
			 * A​l​b​u​m​s
			 */
			albums: string
			/**
			 * A​r​t​i​s​t​s
			 */
			artists: string
			/**
			 * G​e​n​r​e​s
			 */
			genres: string
			/**
			 * L​o​n​g​e​s​t​ ​T​r​a​c​k
			 */
			longestTrack: string
		}
		genreMap: {
			/**
			 * G​e​n​r​e​ ​M​a​p
			 */
			title: string
			/**
			 * f​r​o​m​ ​{​n​}​ ​s​o​n​g​s
			 * @param {unknown} n
			 */
			fromSongs: RequiredParams<'n'>
			/**
			 * C​l​i​c​k​ ​t​o​ ​p​l​a​y
			 */
			clickToPlay: string
		}
		albumsTimeline: {
			/**
			 * Y​o​u​r​ ​l​i​b​r​a​r​y​ ​s​p​a​n​s​ ​<​s​p​a​n​>​{​y​e​a​r​s​}​<​/​s​p​a​n​>​ ​y​e​a​r​s
			 * @param {unknown} years
			 */
			title: RequiredParams<'years'>
			/**
			 * f​r​o​m​ ​{​n​}​ ​a​l​b​u​m​s
			 * @param {unknown} n
			 */
			fromAlbums: RequiredParams<'n'>
			/**
			 * C​l​i​c​k​ ​t​o​ ​p​l​a​y
			 */
			clickToPlay: string
		}
	}
}

export type TranslationFunctions = {
	common: {
		/**
		 * No results
		 */
		noResults: () => LocalizedString
	}
	infoPopup: {
		/**
		 * Built by
		 */
		builtBy: () => LocalizedString
		/**
		 * and contributors
		 */
		andContributors: () => LocalizedString
		/**
		 * version
		 */
		version: () => LocalizedString
		/**
		 * Release Notes
		 */
		releaseNotes: () => LocalizedString
	}
	sidebar: {
		/**
		 * Search
		 */
		search: () => LocalizedString
		/**
		 * Library
		 */
		library: () => LocalizedString
		/**
		 * Albums
		 */
		albums: () => LocalizedString
		/**
		 * Favourites
		 */
		favorites: () => LocalizedString
		/**
		 * To Delete
		 */
		toDelete: () => LocalizedString
		/**
		 * Playlists
		 */
		playlists: () => LocalizedString
		/**
		 * Smart Playlists
		 */
		smartPlaylists: () => LocalizedString
		/**
		 * Artist's Toolkit
		 */
		artistsToolkit: () => LocalizedString
		/**
		 * Map
		 */
		map: () => LocalizedString
		/**
		 * Internet Archive
		 */
		internetArchive: () => LocalizedString
		/**
		 * Stats
		 */
		stats: () => LocalizedString
		/**
		 * Open Wiki panel for {artist}
		 */
		openWikiTooltip: (arg: { artist: unknown }) => LocalizedString
		/**
		 * Add metadata
		 */
		addMetadataHint: () => LocalizedString
		/**
		 * Take control of your library
		 */
		takeControl: () => LocalizedString
		/**
		 * Main player off in Internet Archive mode<br /><br />Stop playback to re-enable
		 */
		iaMode: () => LocalizedString
	}
	library: {
		fields: {
			/**
			 * Title
			 */
			title: () => LocalizedString
			/**
			 * Artist
			 */
			artist: () => LocalizedString
			/**
			 * Composer
			 */
			composer: () => LocalizedString
			/**
			 * Album
			 */
			album: () => LocalizedString
			/**
			 * Album Artist
			 */
			albumArtist: () => LocalizedString
			/**
			 * Track
			 */
			track: () => LocalizedString
			/**
			 * Compil
			 */
			compilation: () => LocalizedString
			/**
			 * Year
			 */
			year: () => LocalizedString
			/**
			 * Date Added
			 */
			dateAdded: () => LocalizedString
			/**
			 * Genre
			 */
			genre: () => LocalizedString
			/**
			 * Origin
			 */
			origin: () => LocalizedString
			/**
			 * Duration
			 */
			duration: () => LocalizedString
			/**
			 * Tags
			 */
			tags: () => LocalizedString
		}
		empty: {
			/**
			 * Click "Import library" or just drag + drop a folder here
			 */
			title: () => LocalizedString
			/**
			 * You can always add more music later
			 */
			subtitle: () => LocalizedString
			/**
			 * Import library +
			 */
			'import': () => LocalizedString
			/**
			 * Supports MP3, FLAC, OGG, AAC and WAV
			 */
			formats: () => LocalizedString
			/**
			 * or add folders to watch
			 */
			addFoldersToWatch: () => LocalizedString
			/**
			 * 🥁Importing...
			 */
			importing: () => LocalizedString
		}
		/**
		 * Reset to file order
		 */
		resetToFileOrder: () => LocalizedString
		/**
		 * Showing file order
		 */
		orderHint: () => LocalizedString
		/**
		 * Showing temporary order
		 */
		orderHintTemp: () => LocalizedString
		/**
		 * Switch to file order to re-order tracks
		 */
		orderDisabledHint: () => LocalizedString
		/**
		 * No results for "{query}"
		 */
		queryNoResultsPlaceholder: (arg: { query: unknown }) => LocalizedString
		/**
		 * Reset order and sizes
		 */
		resetColumns: () => LocalizedString
		/**
		 * Reset sizes only
		 */
		resetSizesOnly: () => LocalizedString
	}
	bottomBar: {
		/**
		 * Queue
		 */
		queue: () => LocalizedString
		/**
		 * Lyrics
		 */
		lyrics: () => LocalizedString
		/**
		 * Wiki
		 */
		wiki: () => LocalizedString
		lossySelector: {
			/**
			 * lossy
			 */
			lossy: () => LocalizedString
			/**
			 * lossless
			 */
			lossless: () => LocalizedString
			/**
			 * lossy + lossless
			 */
			both: () => LocalizedString
		}
		/**
		 * Waveform
		 */
		waveform: () => LocalizedString
		/**
		 * Equalizer
		 */
		equalizer: () => LocalizedString
		/**
		 * Select preset
		 */
		selectPreset: () => LocalizedString
		/**
		 * Next Up
		 */
		nextUp: () => LocalizedString
		stats: {
			/**
			 * songs
			 */
			songs: () => LocalizedString
			/**
			 * artists
			 */
			artists: () => LocalizedString
			/**
			 * albums
			 */
			albums: () => LocalizedString
		}
	}
	smartPlaylists: {
		builtIn: {
			/**
			 * Recently Added
			 */
			recentlyAdded: () => LocalizedString
			/**
			 * Favourites
			 */
			favourites: () => LocalizedString
			/**
			 * With Stems
			 */
			withStems: () => LocalizedString
		}
		builder: {
			/**
			 * Close editor
			 */
			close: () => LocalizedString
			/**
			 * Save
			 */
			save: () => LocalizedString
			/**
			 * My New Smart Playlist
			 */
			placeholder: () => LocalizedString
			/**
			 * add new block
			 */
			addNewBlock: () => LocalizedString
			/**
			 * query is valid
			 */
			valid: () => LocalizedString
			/**
			 * query is invalid
			 */
			invalid: () => LocalizedString
			parts: {
				byAlbumArtist: {
					/**
					 * by album artist
					 */
					title: () => LocalizedString
					/**
					 * eg. by Charlie Parker
					 */
					example: () => LocalizedString
				}
				byArtist: {
					/**
					 * by artist
					 */
					title: () => LocalizedString
					/**
					 * eg. by Charlie Parker
					 */
					example: () => LocalizedString
				}
				releasedBetween: {
					/**
					 * released between
					 */
					title: () => LocalizedString
					/**
					 * eg. released between 1950 and 1967
					 */
					example: () => LocalizedString
				}
				releasedAfter: {
					/**
					 * released after
					 */
					title: () => LocalizedString
					/**
					 * eg. released after 1950
					 */
					example: () => LocalizedString
				}
				releasedIn: {
					/**
					 * released in
					 */
					title: () => LocalizedString
					/**
					 * eg. released in 1999
					 */
					example: () => LocalizedString
				}
				titleContains: {
					/**
					 * song title contains [text]
					 */
					title: () => LocalizedString
					/**
					 *  eg. title contains Love
					 */
					example: () => LocalizedString
				}
				longerThan: {
					/**
					 * longer than
					 */
					title: () => LocalizedString
					/**
					 * eg. longer than 04:00
					 */
					example: () => LocalizedString
				}
				containsGenre: {
					/**
					 * contains genre
					 */
					title: () => LocalizedString
					/**
					 * eg. contains Rock
					 */
					example: () => LocalizedString
				}
				fromCountry: {
					/**
					 * from country
					 */
					title: () => LocalizedString
					/**
					 * eg. from Australia
					 */
					example: () => LocalizedString
				}
				byComposer: {
					/**
					 * by composer
					 */
					title: () => LocalizedString
					/**
					 * eg. by Charles Mingus
					 */
					example: () => LocalizedString
				}
				containsTag: {
					/**
					 * contains tag
					 */
					title: () => LocalizedString
					/**
					 * eg. contains love
					 */
					example: () => LocalizedString
				}
				hasStems: {
					/**
					 * has stems
					 */
					title: () => LocalizedString
				}
			}
		}
		/**
		 * Edit smart playlist
		 */
		editSmartPlaylist: () => LocalizedString
		/**
		 * New smart playlist
		 */
		newSmartPlaylist: () => LocalizedString
		libraryPlaceholder: {
			/**
			 * Smart playlist results will appear here
			 */
			title: () => LocalizedString
			/**
			 * Happy searching!
			 */
			subtitle: () => LocalizedString
		}
	}
	trackInfo: {
		/**
		 * Track Info
		 */
		title: () => LocalizedString
		/**
		 * Use ↑ and ↓ to change tracks
		 */
		subtitle: () => LocalizedString
		/**
		 * Overwrite file
		 */
		overwriteFile: () => LocalizedString
		/**
		 * File Info
		 */
		fileInfo: () => LocalizedString
		/**
		 * File
		 */
		file: () => LocalizedString
		/**
		 * Codec
		 */
		codec: () => LocalizedString
		/**
		 * Tag Type
		 */
		tagType: () => LocalizedString
		/**
		 * Duration
		 */
		duration: () => LocalizedString
		/**
		 * Sample rate
		 */
		sampleRate: () => LocalizedString
		/**
		 * Bitrate
		 */
		bitRate: () => LocalizedString
		/**
		 * Enrichment Center
		 */
		enrichmentCenter: () => LocalizedString
		/**
		 * Save
		 */
		save: () => LocalizedString
		metadata: {
			/**
			 * Metadata
			 */
			title: () => LocalizedString
			saveTooltip: {
				/**
				 * Pending changes
				 */
				title: () => LocalizedString
				/**
				 * added
				 */
				added: () => LocalizedString
				/**
				 * removed
				 */
				removed: () => LocalizedString
				/**
				 * changed
				 */
				modified: () => LocalizedString
				/**
				 * ⌘ + Enter to save
				 */
				hint: () => LocalizedString
			}
		}
		enrichment: {
			country: {
				/**
				 * Country of Origin
				 */
				title: () => LocalizedString
				/**
				 * Set this to use the Map view and filter by country in Smart Playlists
				 */
				infoTooltip: () => LocalizedString
				fetchButton: {
					/**
					 * Fetch
					 */
					title: () => LocalizedString
					/**
					 * Loading...
					 */
					loading: () => LocalizedString
					/**
					 * Fetch country of origin from Wikipedia
					 */
					tooltip: () => LocalizedString
				}
				saveButton: {
					/**
					 * Save
					 */
					title: () => LocalizedString
				}
				/**
				 * Country enrichment not available when using read-only beets database.
				 */
				disabled: () => LocalizedString
			}
		}
		artwork: {
			saveButton: {
				/**
				 * Write to file
				 */
				file: () => LocalizedString
				/**
				 * Save {file} to folder
				 */
				folder: (arg: { file: unknown }) => LocalizedString
				/**
				 * Delete {file} in folder
				 */
				deleteFolderArt: (arg: { file: unknown }) => LocalizedString
			}
			fetchButton: {
				/**
				 * Fetch art
				 */
				title: () => LocalizedString
				/**
				 * Fetch art from Wikipedia, Musicbrainz, Genius or Discogs and save to album folder
				 */
				tooltip: () => LocalizedString
			}
			searchButton: {
				/**
				 * Search art
				 */
				title: () => LocalizedString
				/**
				 * Open a browser search for the album cover
				 */
				tooltip: () => LocalizedString
			}
			/**
			 * Click to replace, or paste an image
			 */
			pasteTooltip: () => LocalizedString
		}
		/**
		 * Ready to save
		 */
		artworkReadyToSave: () => LocalizedString
		/**
		 * Found
		 */
		artworkFound: () => LocalizedString
		/**
		 * No artwork
		 */
		noArtwork: () => LocalizedString
		/**
		 * Multiple artworks
		 */
		multiArtwork: () => LocalizedString
		/**
		 * Paste image or click to select file
		 */
		artworkTooltip: () => LocalizedString
		/**
		 * Tools
		 */
		tools: () => LocalizedString
		/**
		 * About artwork
		 */
		aboutArtwork: () => LocalizedString
		/**
		 * 🎨 Artwork priority
		 */
		artworkTooltipTitle: () => LocalizedString
		/**
		 * <h3 style='margin:0'>🎨 Artwork priority</h3><br/>First, Musicat looks for artwork encoded in the file metadata, which you can overwrite by clicking this square (png and jpg supported). <br/><br/>If there is none, it will look for a file in the album folder called <i>cover.jpg, folder.jpg</i> or <i>artwork.jpg</i> (you can change this list of filenames in Settings).<br/><br/>Otherwise, it will look for any image in the album folder and use that.
		 */
		artworkTooltipBody: () => LocalizedString
		/**
		 * In metadata
		 */
		encodedInFile: () => LocalizedString
		/**
		 * bit
		 */
		bit: () => LocalizedString
		/**
		 * Song has no metadata
		 */
		noMetadata: () => LocalizedString
		/**
		 * This file type is not yet supported for metadata viewing/editing
		 */
		unsupportedFormat: () => LocalizedString
		/**
		 * Fix
		 */
		fix: () => LocalizedString
		errors: {
			/**
			 * Some tags have a hidden character that prevents them from being read properly.
			 */
			nullChars: () => LocalizedString
		}
		/**
		 * artist
		 */
		artist: () => LocalizedString
		fixLegacyEncodings: {
			/**
			 * Fix legacy encodings
			 */
			title: () => LocalizedString
			/**
			 * If you have ID3 tags encoded with legacy encodings, you should update them to the universal UTF-8 so they display properly. Select an encoding and click Fix.
			 */
			body: () => LocalizedString
			/**
			 * Select encoding...
			 */
			hint: () => LocalizedString
		}
		/**
		 * Click to set title from filename
		 */
		setTitleFromFileNameHint: () => LocalizedString
		/**
		 * Metadata not supported when selecting songs with different tag types
		 */
		differentTagTypes: () => LocalizedString
	}
	settings: {
		/**
		 * Settings
		 */
		title: () => LocalizedString
		/**
		 * Library
		 */
		library: () => LocalizedString
		/**
		 * Audio
		 */
		audio: () => LocalizedString
		/**
		 * Output device
		 */
		outputDevice: () => LocalizedString
		/**
		 * Same as system device
		 */
		followSystem: () => LocalizedString
		/**
		 * Interface
		 */
		'interface': () => LocalizedString
		/**
		 * Mini Player Location
		 */
		miniPlayerLocation: () => LocalizedString
		/**
		 * Language
		 */
		language: () => LocalizedString
		/**
		 * Theme
		 */
		theme: () => LocalizedString
		/**
		 * Use system theme
		 */
		followSystemTheme: () => LocalizedString
		/**
		 * Features
		 */
		features: () => LocalizedString
		/**
		 * Configure stuff
		 */
		subtitle: () => LocalizedString
		/**
		 * Version
		 */
		version: () => LocalizedString
		/**
		 * filenames
		 */
		commaSeparatedFilenames: () => LocalizedString
		/**
		 * gpt-3.5-turbo, gpt-4, ollama
		 */
		llms: () => LocalizedString
		/**
		 * Folders to watch
		 */
		foldersToWatch: () => LocalizedString
		/**
		 * {{1 folder|?? folders}}
		 */
		folder: (arg0: number | string | boolean) => LocalizedString
		/**
		 * Importing..
		 */
		importing: () => LocalizedString
		/**
		 * Cover art filenames
		 */
		coverArtFilenames: () => LocalizedString
		/**
		 * Enable Artist's Toolkit
		 */
		enableArtistsToolkit: () => LocalizedString
		/**
		 * Import
		 */
		'import': () => LocalizedString
		/**
		 * Enable Cover Art check
		 */
		enableCoverArtCheck: () => LocalizedString
		/**
		 * Songbook location
		 */
		songbookLocation: () => LocalizedString
		/**
		 * Scrapbook location
		 */
		scrapbookLocation: () => LocalizedString
		/**
		 * Download location
		 */
		downloadLocation: () => LocalizedString
		/**
		 * Generated stems location
		 */
		generatedStemsLocation: () => LocalizedString
		/**
		 * Playlists location
		 */
		playlistsLocation: () => LocalizedString
		/**
		 * Enable AI features
		 */
		enableAIFeatures: () => LocalizedString
		/**
		 * AI Model (LLM)
		 */
		aiModel: () => LocalizedString
		/**
		 * OpenAI API Key
		 */
		openApiKey: () => LocalizedString
		/**
		 * Genius API Key
		 */
		geniusApiKey: () => LocalizedString
		/**
		 * Discogs API Key
		 */
		discogsApiKey: () => LocalizedString
		/**
		 * Beets database location
		 */
		beetsDbLocation: () => LocalizedString
	}
	wiki: {
		/**
		 * Found mentions from your library:
		 */
		inArticle: () => LocalizedString
		/**
		 * Click to scroll to mention
		 */
		clickHint: () => LocalizedString
		/**
		 * Albums
		 */
		albums: () => LocalizedString
		/**
		 * Songs
		 */
		songs: () => LocalizedString
		/**
		 * Artists
		 */
		artists: () => LocalizedString
	}
	tagCloud: {
		/**
		 * Close tags
		 */
		close: () => LocalizedString
	}
	artistsToolkit: {
		header: {
			/**
			 * Your songbook location managed by Musicat. Currently set to {path}
			 */
			songbookLocationHint: (arg: { path: unknown }) => LocalizedString
			/**
			 * Please set your songbook location to be managed by Musicat.
			 */
			songbookLocationHintEmpty: () => LocalizedString
			/**
			 * Show scrapbook
			 */
			showScrapbook: () => LocalizedString
			/**
			 * Hide scrapbook
			 */
			hideScrapbook: () => LocalizedString
		}
		scrapbook: {
			/**
			 * Scrapbook
			 */
			title: () => LocalizedString
			/**
			 * Please set up your scrapbook location in settings
			 */
			setupHint: () => LocalizedString
			/**
			 * Scrapbook location not found
			 */
			notFoundError: () => LocalizedString
			/**
			 * Open settings
			 */
			openSettings: () => LocalizedString
			/**
			 * Open in Finder
			 */
			openInFinder: () => LocalizedString
		}
		songDetails: {
			tabs: {
				/**
				 * Lyrics & Chords
				 */
				lyrics: () => LocalizedString
				/**
				 * Files
				 */
				files: () => LocalizedString
				/**
				 * Other
				 */
				other: () => LocalizedString
			}
			lyricsEditor: {
				options: {
					/**
					 * Align 1st chord
					 */
					alignFirstChord: () => LocalizedString
				}
			}
		}
	}
	button: {
		/**
		 * Click again to confirm
		 */
		areYouSure: () => LocalizedString
	}
	input: {
		/**
		 * Press ENTER to autocomplete
		 */
		enterHintTooltip: () => LocalizedString
	}
	albums: {
		/**
		 * Albums
		 */
		title: () => LocalizedString
		options: {
			/**
			 * order by
			 */
			orderBy: () => LocalizedString
			orderByFields: {
				/**
				 * Title
				 */
				title: () => LocalizedString
				/**
				 * Artist
				 */
				artist: () => LocalizedString
				/**
				 * Year
				 */
				year: () => LocalizedString
			}
			/**
			 * singles
			 */
			showSingles: () => LocalizedString
			/**
			 * info
			 */
			showInfo: () => LocalizedString
			/**
			 * grid size
			 */
			gridSize: () => LocalizedString
		}
		/**
		 * Scroll to Now playing
		 */
		scrollToNowPlaying: () => LocalizedString
		item: {
			/**
			 * tracks
			 */
			tracksLabel: () => LocalizedString
		}
	}
	albumMenu: {
		/**
		 * Re-import Album
		 */
		reImportAlbum: () => LocalizedString
		/**
		 * ⚡️ Enrich
		 */
		enrich: () => LocalizedString
		/**
		 * Origin country
		 */
		originCountry: () => LocalizedString
		/**
		 * Origin country ✅
		 */
		originCountryC: () => LocalizedString
		/**
		 * from Wikipedia
		 */
		originCountryHint: () => LocalizedString
		/**
		 * Fetch artwork from Wikipedia
		 */
		fetchArtwork: () => LocalizedString
		/**
		 * Save to folder as cover.jpg
		 */
		fetchArtworkHint: () => LocalizedString
		/**
		 * Fetching from Wikipedia...
		 */
		fetchFromWikipedia: () => LocalizedString
		/**
		 * Scan existing artwork
		 */
		scanExistingArtwork: () => LocalizedString
		/**
		 * Rescanning...
		 */
		scanningExistingArtwork: () => LocalizedString
		/**
		 * Check encoded art in tracks / folder image
		 */
		scanExistingArtworkHint: () => LocalizedString
		/**
		 * Search for artwork on Brave
		 */
		searchFromBrave: () => LocalizedString
		/**
		 * Wiki page:
		 */
		wikiPanel: () => LocalizedString
		/**
		 * Remove album from library
		 */
		removeFromLibrary: () => LocalizedString
		/**
		 * Open in {explorerName}
		 */
		openInFileManager: (arg: { explorerName: unknown }) => LocalizedString
		/**
		 * Info & Metadata
		 */
		infoMetadata: () => LocalizedString
	}
	trackMenu: {
		/**
		 * Re-Import Track
		 */
		reImportTrack: () => LocalizedString
		/**
		 * Re-import {n} tracks
		 */
		reImportTracks: (arg: { n: unknown }) => LocalizedString
		/**
		 * Will also re-import albums
		 */
		reImportTrackHint: () => LocalizedString
		/**
		 * Stems (click to play)
		 */
		separateTitle: () => LocalizedString
		/**
		 * Separate stems
		 */
		separateStems: () => LocalizedString
		/**
		 * Edit tags
		 */
		editTag: () => LocalizedString
		/**
		 * ⚡️ Enrich
		 */
		enrich: () => LocalizedString
		/**
		 * Looking online...
		 */
		lookingOnline: () => LocalizedString
		/**
		 * Wiki panel:
		 */
		wikiPanel: () => LocalizedString
		/**
		 * Remove {{track|?? tracks}} from library
		 */
		removeFromLibrary: (arg0: number | string | boolean) => LocalizedString
		/**
		 * Delete {{file|?? files}}
		 */
		deleteFile: (arg0: number | string | boolean) => LocalizedString
		/**
		 * Move to system Trash / Recycle bin
		 */
		deleteFileHint: () => LocalizedString
		/**
		 * More tools
		 */
		moreTools: () => LocalizedString
		/**
		 * Unselect all
		 */
		unselectAll: () => LocalizedString
		/**
		 * Remove track from queue
		 */
		removeTrackFromQueue: () => LocalizedString
		/**
		 * Remove tracks from queue
		 */
		removeTracksFromQueue: () => LocalizedString
		/**
		 * Origin country
		 */
		originCountry: () => LocalizedString
		/**
		 * Origin country ✅
		 */
		originCountryC: () => LocalizedString
		/**
		 * from Wikipedia
		 */
		originCountryHint: () => LocalizedString
		/**
		 * Open in {explorerName}
		 */
		openInFileManager: (arg: { explorerName: unknown }) => LocalizedString
		/**
		 * Info & Metadata
		 */
		infoMetadata: () => LocalizedString
	}
	toolsMenu: {
		/**
		 * ⚡️ Enrich
		 */
		enrich: () => LocalizedString
		/**
		 * Looking online...
		 */
		lookingOnline: () => LocalizedString
		/**
		 * Origin country
		 */
		originCountry: () => LocalizedString
		/**
		 * Origin country ✅
		 */
		originCountryC: () => LocalizedString
		/**
		 * from Wikipedia
		 */
		originCountryHint: () => LocalizedString
		/**
		 * Chords:
		 */
		chords: () => LocalizedString
		/**
		 * Lyrics:
		 */
		lyrics: () => LocalizedString
		/**
		 * Wiki panel:
		 */
		wikiPanel: () => LocalizedString
	}
	toDelete: {
		/**
		 * To Delete
		 */
		title: () => LocalizedString
		/**
		 * Tracks to delete from Prune Mode
		 */
		description: () => LocalizedString
		/**
		 * Keep all
		 */
		keepAllBtn: () => LocalizedString
		/**
		 * Move all to trash
		 */
		deleteAllBtn: () => LocalizedString
		notification: {
			/**
			 * Deleting {{track|?? tracks}}
			 */
			deleting: (arg0: number | string | boolean) => LocalizedString
			/**
			 * Deleted {{track|?? tracks}}
			 */
			deleted: (arg0: number | string | boolean) => LocalizedString
		}
	}
	lyrics: {
		/**
		 * Auto scroll
		 */
		autoScroll: () => LocalizedString
		/**
		 * Using local lyrics file
		 */
		localLyrics: () => LocalizedString
		/**
		 * Using Genius lyrics
		 */
		geniusLyrics: () => LocalizedString
		/**
		 * Using LRC.LIB lyrics
		 */
		lrcLibLyrics: () => LocalizedString
	}
	stemSeparation: {
		/**
		 * Separating vocal & instrumental...
		 */
		loading: () => LocalizedString
		/**
		 * Separation complete
		 */
		complete: () => LocalizedString
		/**
		 * Error: {{error}}
		 */
		error: (arg0: number | string | boolean) => LocalizedString
		/**
		 * Show stems
		 */
		showStems: () => LocalizedString
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
		/**
		 * Close
		 */
		close: () => LocalizedString
	}
	updater: {
		/**
		 * Checking for updates…
		 */
		checking: () => LocalizedString
		/**
		 * Update available
		 */
		available: () => LocalizedString
		/**
		 * Downloading… {percent}%
		 */
		downloading: (arg: { percent: unknown }) => LocalizedString
		/**
		 * Installing update…
		 */
		installing: () => LocalizedString
		/**
		 * Musicat is up to date.
		 */
		upToDate: () => LocalizedString
		/**
		 * Update check failed.
		 */
		checkFailed: () => LocalizedString
		/**
		 * Install
		 */
		install: () => LocalizedString
		/**
		 * Later
		 */
		later: () => LocalizedString
		/**
		 * OK
		 */
		ok: () => LocalizedString
		/**
		 * Update available
		 */
		titleAvailable: () => LocalizedString
		/**
		 * Downloading update…
		 */
		titleDownloading: () => LocalizedString
		/**
		 * Installing update…
		 */
		titleInstalling: () => LocalizedString
		/**
		 * Up to date
		 */
		titleUpToDate: () => LocalizedString
		/**
		 * Update failed
		 */
		titleError: () => LocalizedString
	}
	analytics: {
		summary: {
			/**
			 * Summary
			 */
			title: () => LocalizedString
			/**
			 * Total Songs
			 */
			totalSongs: () => LocalizedString
			/**
			 * Albums
			 */
			albums: () => LocalizedString
			/**
			 * Artists
			 */
			artists: () => LocalizedString
			/**
			 * Genres
			 */
			genres: () => LocalizedString
			/**
			 * Longest Track
			 */
			longestTrack: () => LocalizedString
		}
		genreMap: {
			/**
			 * Genre Map
			 */
			title: () => LocalizedString
			/**
			 * from {n} songs
			 */
			fromSongs: (arg: { n: unknown }) => LocalizedString
			/**
			 * Click to play
			 */
			clickToPlay: () => LocalizedString
		}
		albumsTimeline: {
			/**
			 * Your library spans <span>{years}</span> years
			 */
			title: (arg: { years: unknown }) => LocalizedString
			/**
			 * from {n} albums
			 */
			fromAlbums: (arg: { n: unknown }) => LocalizedString
			/**
			 * Click to play
			 */
			clickToPlay: () => LocalizedString
		}
	}
}

export type Formatters = {}
