import type { Theme } from "../types/theme.d.ts";

import tmLight from "./themes/light.yaml";
import tmZokugunObsidium from "./themes/zokugun-obsidium.yaml";

export const allFonts = {
    "2Peas": {
        "--font": "2Peas",
    },
};

export const DEFAULT_THEME: Theme = {
    "display-name": "Dark",
    type: "dark",
    text: "#ffffffde",
    "text-secondary": "#9fa0a2",
    "text-active": "#ffffff",
    "text-inactive": "#938e8e",
    background: "#242026cb",
    "overlay-bg": "#3c3c3f33",
    "overlay-shadow": "#00000042",
    accent: "#45fffcf3",
    "accent-secondary": "#632fff",
    "icon-boxed-hover-bg": "#rgba(0, 0, 0, 0.187)",
    "icon-disabled": "#474747",
    "icon-primary": "#ffffff",
    "icon-secondary": "#948f8f",
    "icon-secondary-hover": "rgb(from var(--icon-secondary) r g b / 0.4)",
    "icon-tertiary": "var(--accent-secondary)",
    "icon-tertiary-hover": "rgb(from var(--icon-tertiary) r g b / 0.4)",
    "button-bg": "#1c1b1b",
    "button-text": "#ffffff",
    "input-alt-focus-outline": "1px solid #c4c7c8",
    "input-bg": "#4d494966",
    "input-focus-outline": "2px solid #7171bb",
    "header-opacity": 0.2,
    "header-text": "var(--text)",
    link: "#acafff",
    "link-hover": "#8086ff",
    title: "#7dffee",
    "atk-icon-audio": "#c745c7",
    "atk-icon-link": "#46e3e3",
    "atk-icon-lyric": "#d4d442",
    "atk-icon-video": "#e04848",
    "menu-bg": "#20202296",
    "menu-border": "#ffffff3b",
    "menu-checkbox-off": "#808080",
    "menu-checkbox-on": "#ffffff",
    "menu-divider": "#494949",
    "menu-item-confirm-bg": "#d2630e",
    "menu-item-destructive-hover-bg": "#d20e32",
    "menu-item-destructive-hover-text": "#ffffff",
    "menu-item-disabled": "#aeaeae66",
    "menu-item-highlight-bg": "#ffffffcb",
    "menu-item-highlight-border": "transparent",
    "menu-item-highlight-text": "#252424",
    "menu-item-highlight-secondary-bg": "#ffffff32",
    "menu-item-highlight-secondary-border": "#ffffff1a",
    "menu-item-highlight-secondary-text": "#ffffff",
    "menu-item-loading-from": "inherit",
    "menu-item-loading-to": "#dba4fac1",
    "menu-item-text": "#ffffff",
    "menu-shadow": "#00000022",
    "transport-control": "#ffffff",
    "transport-control-hover": "rgb(from var(--transport-control) r g b / 0.5)",
    "transport-favorite": "#59cd7a",
    "transport-favorite-hover":
        "rgb(from var(--transport-favorite) r g b / 0.4)",
    "transport-shuffle": "#e1ff00",
    "transport-shuffle-hover": "rgb(from var(--transport-shuffle) r g b / 0.4)",
    "transport-volume-line-bg":
        "color-mix(in srgb, var(--inverse) 20%, transparent)",
    "transport-volume-thumb-bg": "#FDFDFD",
    "transport-volume-thumb-icon": "#5123DD",
    "transport-volume-thumb-secondary": "#04aa6d",
    "panel-background": "#242026b3",
    "panel-primary-border-main":
        "color-mix(in srgb, var(--inverse) 40%, transparent)",
    "panel-primary-border-accent1":
        "color-mix(in srgb, var(--inverse) 30%, transparent)",
    "panel-primary-border-accent2":
        "color-mix(in srgb, var(--inverse) 10%, transparent)",
    "panel-secondary-border-main": "#ffffff2a",
    "panel-secondary-border-accent": "#ffffff19",
    "panel-separator": "#ffffff17",
    "library-text-color": "#d3d3d3",
    "library-playing-bg": "#5123dd",
    "library-playing-text": "#00ddff",
    "library-playing-title": "#ffffff",
    "library-title": "#ffffff",
    "library-playing-icon": "#00ddff",
    "library-highlight-bg": "#2e3357",
    "library-hover-bg": "#2e335737",
    "library-header-bg": "#71658e7e",
    "library-header-text": "#ffffffde",
    "library-header-active-bg": "#604d8d",
    "library-clickable-cell-bg": "#71658e1e",
    "library-clickable-cell-hover-bg": "#8c7dae36",
    "library-favourite-icon": "#5123dd",
    "library-favourite-hover-icon": "#784bff",
    "smart-playlist-builder-bg": "#4d347c",
    "smart-playlist-builder-text": "#ffffffde",
    "smart-playlist-builder-block-bg": "#7256be56",
    "smart-playlist-builder-block-focused-bg": "#7256be99",
    "smart-playlist-builder-block-input-bg": "#231b4d45",
    "smart-playlist-builder-block-input-text": "#ffffffde",
    "smart-playlist-button-bg": "#624dd4",
    "smart-playlist-button-disabled": "#747272",
    "smart-playlist-button-disabled-bg": "#4935b8",
    "album-playing-pause-bg": "var(--album-playing-play-bg)",
    "album-playing-pause-border": "var(--album-playing-play-border)",
    "album-playing-pause-icon": "var(--album-playing-play-icon)",
    "album-playing-pause-hover-bg": "var(--album-playing-play-hover-bg)",
    "album-playing-pause-hover-icon": "var(--album-playing-play-hover-icon)",
    "album-playing-play-bg": "#25222b",
    "album-playing-play-border": "#5123dd",
    "album-playing-play-icon": "#ffffff",
    "album-playing-play-hover-bg": "#5123dd",
    "album-playing-play-hover-icon": "#ffffff",
    "album-playing-shadow": "#5123dd",
    "album-playing-title-bg": "#632fff",
    "popup-track-artwork-about": "#82c9df",
    "popup-track-artwork-found": "#44a15e",
    "popup-track-artwork-notfound": "#808080",
    "popup-track-data-field-bg": "#0000001e",
    "popup-track-header-bg":
        "color-mix(in srgb, var(--background) 1%, transparent)",
    "popup-track-header-border":
        "color-mix(in srgb, var(--background) 60%, var(--inverse))",
    "popup-track-metadata-prompt-error": "#6f5757",
    "popup-track-metadata-title": "#ffe6ac",
    "popup-track-metadata-validation-error": "#a12e2e",
    "popup-track-metadata-validation-warning": "#e19a00",
    "popup-track-section-bg":
        "color-mix(in srgb, var(--overlay-bg) 80%, var(--inverse))",
    "popup-track-section-border":
        "color-mix(in srgb, var(--background) 70%, var(--inverse))",
    "popup-track-section-title-bg":
        "color-mix(in srgb, var(--background) 50%, var(--inverse))",
    "popup-track-section-title-text": "var(--title)",
    oscilloscope: "#14D8BD",
    "waveform-bg": "#9c86b10f",
    "waveform-bg-hover": "#9c86b11c",
    "waveform-cursor": "#ffffff",
    "waveform-progress": "#cfbfff",
    "waveform-region-current": "#00C56C",
    "waveform-region-loop": "#DCBCFF3A",
    "waveform-wave": "#64578cca",
    "waveform-hover-label-bg": "transparent",
    "waveform-hover-label-text": "#ffffff",
    "waveform-hover-line": "#f8f8f882",
    "waveform-hoverhead-line-bg": "#FFFFFF62",
    "sidebar-info-artist-active-bg":
        "color-mix(in srgb, var(--inverse) 90%, transparent)",
    "sidebar-info-artist-hover-bg":
        "color-mix(in srgb, var(--inverse) 80%, transparent)",
    "sidebar-info-title-hover-bg":
        "color-mix(in srgb, var(--inverse) 40%, transparent)",
    "sidebar-info-title-hover-border": "var(--inverse)",
    "sidebar-item-drag-bg": "#5123dd",
    "sidebar-item-hover-bg": "#392f5d3b",
    "sidebar-item-hover-text": "var(--text-inactive)",
    "sidebar-item-selected-pipe-bg": "#5123dd",
    "sidebar-node-inactive-hover-bg": "transparent",
    "sidebar-node-inactive-hover-opacity": 0.5,
    "sidebar-node-inactive-hover-text": "var(--text-inactive)",
    "sidebar-player-disabled-bg": "#312d3ec0",
    "sidebar-player-disabled-text": "var(--text)",
    "sidebar-search-focus-bg":
        "color-mix(in srgb, var(--inverse) 80%, transparent);",
    "mapview-region-bg": "#645479",
    "mapview-region-border": "#4F4464",
    "mapview-region-hover-bg": "#645479",
    "mapview-region-hover-border": "#C1B1F3",
    "mapview-region-selected-bg": "#59CD70",
    "mapview-region-selected-border": "#4F4464",
    "mapview-region-selected-hover-bg": "#59CD70",
    "mapview-region-selected-hover-border": "#4F4464",
    "mapview-scale-1": "#eeeeee",
    "mapview-scale-2": "#999999",
    "mapview-tooltip-artist": "#ffffff95",
    "mapview-tooltip-bg": "#232325cc",
    "mapview-tooltip-border": "#ffffff2d",
    "mapview-tooltip-text": "#808080",
    "progressbar-track-bg": "#ffffff43",
    "progressbar-value-bg": "#23DD7F",
    "analytics-border": "rgba(255, 255, 255, 0.11)",
    "analytics-text-primary": "#23dd7f",
    "analytics-text-secondary": "#855dff",
    "analytics-timeline-track-bg": "#ece5e54f",
    "analytics-timeline-vline-bg": "#ece5e54f",
    "prune-button-border": "var(--inverse)",
    "prune-button-delete-bg": "#ff00007d",
    "prune-button-delete-pressed-shadow": "#ff4747aa",
    "prune-button-keep-bg": "#00800073",
    "prune-button-keep-pressed-shadow": "#00ff00aa",
    "prune-fordelete": "#ff5a5a",
    "wiki-bg": "#ffffff18",
    "wiki-close-prompt-bg": "#33303ce2",
    "wiki-close-prompt-text": "#ffffff",
    "wiki-header-bg": "var(--wiki-bg)",
    "wiki-inarticle-bg": "var(--wiki-bg)",
    "wiki-pill-bg": "var(--wiki-bg)",
    "wiki-pill-border": "var(--panel-primary-border-main)",
    "wiki-pill-text": "var(--text-secondary)",
    "wiki-pill-hover-bg":
        "color-mix(in srgb, var(--button-bg) 20%, transparent)",
    "wiki-pill-hover-text": "var(--text-secondary)",
    "scrollto-active-bg": "#2a2a2d",
    "scrollto-active-border": "#656262",
    "scrollto-active-shadow": "#1f1f1fee",
    "scrollto-bg": "#1b1b1c",
    "scrollto-border": "#3a3838",
    "scrollto-eq": "#dddddd",
    "scrollto-hover-bg": "#1f1f21",
    "scrollto-hover-border": "#656262",
    "scrollto-hover-shadow": "#1f1f1fee",
    "scrollto-shadow": "#1f1f1fd5",
    "scrollto-text": "#ffffff",
    "seekbar-hoverhead": "#ffffff",
    "seekbar-line-bg": "color-mix(in srgb, var(--background) 76%, white)",
    "seekbar-thumb": "#00C56C",
};

export const allThemes: { [key: string]: Theme } = {
    light2: {
        ...DEFAULT_THEME,
        "display-name": "Light2",
        type: "light",
        text: "#282230",
        "text-secondary": "#56575b",
        "text-active": "#38353b",
        "text-inactive": "#646067",
        background: "#e9e5efd9",
        "overlay-bg": "#f1f1f1c0",
        accent: "#5d00fff3",
        "accent-secondary": "#da69ff",
        "button-bg": "#282b2c",
        "button-text": "#ede8f0",
        "input-bg": "#86808066",
        "icon-primary": "#2c0b3e",
        "icon-secondary": "#716a6a",
        "transport-control": "#333135",
        "transport-favorite": "#49ab65",
        "transport-shuffle": "#9804d3",
        "panel-background": "#e3dfe8",
        "library-text-color": "#3e4040",
        "library-title": "#282230",
        "library-playing-bg": "#5123dd",
        "library-playing-icon": "#efe2e6",
        "library-playing-text": "#ffffff",
        "library-highlight-bg": "#5123dd45",
        "library-hover-bg": "#5123dd1c",
        "library-header-bg": "#998bbb7e",
        "library-header-text": "#312c2c",
        "library-header-active-bg": "#997be1",
        "library-clickable-cell-bg": "#9891aa1c",
        "library-clickable-cell-hover-bg": "#5123dd6e",
        "library-favourite-icon": "#5123dd",
        "smart-playlist-builder-bg": "#b49bff",
        "smart-playlist-builder-text": "#ffffffde",
        "smart-playlist-builder-block-bg": "#a691f3",
        "smart-playlist-builder-block-focused-bg": "#8b76d0",
        "smart-playlist-builder-block-input-bg": "#907dd1",
        "album-playing-play-hover-bg": "#5123dd",
        "album-playing-shadow": "#5123dd",
        "album-playing-title-bg": "#da69ff",
        oscilloscope: "#590194",
        "scrollto-active-bg": "#c0c0ca",
        "scrollto-active-border": "#65626243",
        "scrollto-active-shadow": "#1f1f1f88",
        "scrollto-bg": "#d9d9e0",
        "scrollto-border": "#a39e9e7f",
        "scrollto-eq": "#a0a0a0",
        "scrollto-hover-bg": "#d2d2dd",
        "scrollto-hover-border": "#6562624f",
        "scrollto-hover-shadow": "#1f1f1f88",
        "scrollto-shadow": "#1f1f1f33",
        "scrollto-text": "var(--text)",
    },
    dark: DEFAULT_THEME,
    amphibian: {
        ...DEFAULT_THEME,
        "display-name": "Amphibian",
        type: "dark",
        text: "#b6e1e3de",
        "text-secondary": "#819be8",
        "text-active": "#83e4ff",
        "text-inactive": "#668e93",
        background: "#233346",
        "overlay-bg": "#2333466d",
        accent: "#00ff62f3",
        "accent-secondary": "#4453bbf3",
        "button-bg": "#486d7b",
        "icon-primary": "#ffffff",
        "icon-secondary": "#797676",
        "transport-control": "#e9d6fb",
        "transport-favorite": "#59cd7a",
        "transport-shuffle": "#e1ff00",
        "panel-background": "#181e25",
        "library-text-color": "#8cb3b8",
        "library-playing-bg": "#23cedd",
        "library-playing-text": "#444444",
        "library-playing-title": "#000000",
        "library-title": "#eeeeee",
        "library-playing-icon": "#1a1718",
        "library-highlight-bg": "#2e4f57",
        "library-hover-bg": "#1d2a30",
        "library-header-bg": "#65888e7e",
        "library-header-active-bg": "#4d788d",
        "library-clickable-cell-bg": "#286e7f46",
        "library-clickable-cell-hover-bg": "#188da5ae",
        "library-favourite-icon": "#23cedd",
        "library-favourite-hover-icon": "#83dbe6",
        "smart-playlist-builder-bg": "#347c75",
        "smart-playlist-builder-block-bg": "#56beb556",
        "smart-playlist-builder-block-focused-bg": "#569abe99",
        "smart-playlist-builder-block-input-bg": "#1b474d6f",
        "album-playing-play-hover-bg": "#23cedd",
        "album-playing-shadow": "#23cedd",
        "album-playing-title-bg": "#4453bbf3",
    },
    turquoise: {
        ...DEFAULT_THEME,
        "display-name": "Turquoise",
        type: "dark",
        background: "#01796fda",
        text: "#eef4f1",
        "text-secondary": "#e4d7c7ff",
        "text-active": "#ffffff",
        "text-inactive": "#a3ccc5",
        accent: "#45fffcf3",
        "accent-secondary": "#32ceb5f3",
        "overlay-bg": "#02564fc6",
        "panel-background": "#027167",
        "button-bg": "#282b2c",
        "button-text": "#ede8f0",
        "input-bg": "#0c5f58da",
        "icon-primary": "white",
        "icon-secondary": "white",
        "library-text-color": "#e4eced",
        "library-header-bg": "#03867b",
        "library-header-active-bg": "#59b5ad",
        "library-playing-bg": "#f3d2ba",
        "library-highlight-bg": "#f3caad82",
        "library-hover-bg": "#f4ceb238",
        "library-playing-text": "#444444",
        "library-playing-title": "#3d1507",
        "library-playing-icon": "#073d23",
        "library-favourite-icon": "#f3d2ba",
        "library-favourite-hover-icon": "#f6decd",
        "library-clickable-cell-bg": "#03867b",
        "library-clickable-cell-hover-bg": "#0ca89b",
        "smart-playlist-builder-bg": "#d6d5d0",
        "smart-playlist-builder-block-bg": "#eee3e3",
        "smart-playlist-builder-block-focused-bg": "#f5efef",
        "smart-playlist-builder-block-input-bg": "#d6e1e090",
        "smart-playlist-builder-block-input-text": "#675c5cde",
        "smart-playlist-builder-text": "#1c4531",
        "album-playing-play-hover-bg": "#f3d2ba",
        "album-playing-shadow": "#f3d2ba",
        "album-playing-title-bg": "#32ceb5f3",
        oscilloscope: "#d2ff2e",
    },
    red: {
        ...DEFAULT_THEME,
        "display-name": "Red",
        text: "#f1f1f1",
        background: "#562931",
        "accent-secondary": "#be3153f3",
        "library-playing-bg": "#be3153",
        "library-playing-text": "#ffffff",
        "library-playing-icon": "#ffffff",
        "library-favourite-icon": "#ff386a",
        "library-favourite-hover-icon": "#ff899d",
        "album-playing-play-hover-bg": "#be3153f3",
        "album-playing-shadow": "#be3153",
        "album-playing-title-bg": "#be3153f3",
        "transport-control": "#be3153",
        "transport-favorite": "#ff386a",
        "transport-shuffle": "#be3153",
    },
    winamp: {
        ...DEFAULT_THEME,
        "display-name": "Winamp",
        type: "dark",
        background: "#25253e",
        "panel-background": "black",
        "library-text-color": "#05A101",
        "library-playing-bg": "transparent",
        "library-playing-text": "white",
        "library-header-bg": "black",
        "library-header-text": "#acb4ac",
        "library-playing-icon": "#7fbd7f",
        "library-favourite-icon": "#05A101",
        "library-favourite-hover-icon": "#7fbd7f",
        "album-playing-play-hover-bg": "#7c715cf3",
        "album-playing-shadow": "transparent",
        "album-playing-title-bg": "#7c715cf3",
        accent: "#F0D895",
        "accent-secondary": "#7c715cf3",
        "text-active": "#F0D895",
        "text-inactive": "#aeafa8",
        "icon-primary": "#E5F6F7",
        "icon-secondary": "#E5F6F7",
        oscilloscope: "#07ea03",
    },
    light: tmLight,
    "zokugun-obsidium": tmZokugunObsidium,
};

export const lightThemes = {
    light: tmLight,
    light2: allThemes.light2,
};

export const darkThemes = {
    amphibian: allThemes.amphibian,
    dark: allThemes.dark,
    turquoise: allThemes.turquoise,
    red: allThemes.red,
    winamp: allThemes.winamp,
    "zokugun-obsidium": tmZokugunObsidium,
};
